[build]
  publish = "public"
  functions = "functions"
  command = "hugo --gc --minify"

[build.environment]
  NODE_VERSION = "16.9.1"
  NPM_VERSION = "7.21.1"

[context.production]
  command = "npm run build"
  HUGO_version = "0.83.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.88.1"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[[redirects]]
  from = "/npmjs/*"
  to = "/npmjs/"
  status = 200
