[[docs]]
    name = "Overview"
    weight = 10
    identifier = "overview"
    url = "/docs/overview/"

[[docs]]
    name = "User Interface"
    weight = 15
    identifier = "user-interface"
    url = "/docs/user-interface/"

[[docs]]
    name = "External partners"
    weight = 15
    identifier = "external-partners"
    url = "/docs/external-partners/"

[[docs]]
    name = "Search strategies"
    weight = 20
    identifier = "search-strategies"
    url = "/docs/search-strategies/"

[[main]]
  name = "Documentation"
  url = "/docs/overview/introduction/"
  weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
