[[docs]]
    name = "Overview"
    weight = 10
    identifier = "overview"
    url = "/docs/overview/"

[[docs]]
    name = "User Interface"
    weight = 15
    identifier = "user-interface"
    url = "/docs/user-interface/"

[[docs]]
    name = "Search strategies"
    weight = 20
    identifier = "search-strategies"
    url = "/docs/search-strategies/"

[[docs]]
  name = "Prologue"
  weight = 100
  identifier = "prologue"
  url = "/docs/prologue/"

[[main]]
  name = "Documentation"
  url = "/docs/prologue/introduction/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 60



# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
