[[docs]]
    name = "Overview"
    weight = 10
    identifier = "overview"
    url = "/docs/overview/"


[[docs]]
  name = "Business models"
  weight= 11
  identifier = "business-models"
  url = "/docs/business-models"

[[docs]]
    name = "Seller features"
    weight = 12
    identifier = "seller-features"
    url = "/docs/user-interface/"

[[docs]]
    name = "External partners"
    weight = 25
    identifier = "external-partners"
    url = "/docs/external-partners/"

[[docs]]
    name = "Search strategies"
    weight = 20
    identifier = "search-strategies"
    url = "/docs/search-strategies/"

[[main]]
  name = "Documentation"
  url = "/docs/overview/introduction/"
  weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
